POST http://0.0.0.0:8000/config
Content-Type: application/json

{
  "picam_config": {
    
    "framerate": 30,
    "resolution_4:3": [
      [640, 480],
      [1024, 768],
      [1640, 1232]
    ],
    "resolution_16:9": [
      [1280, 730],
      [1640, 922],
      [1920, 1080]
    ],
    "awb_mode": "cloudy",
    "awb_gains": 1.9,
    "exposure_mode": "auto"
  },
  "gif_config": {
    "gif_duration": 50,
    "loop_gif": 0,
    "image_magic_installed": "false"
  },
  "general_config": {
    "output_format": "gif",
    "camera": "PiCam",
    "draw_bbox": "false",
    "verbose": "true",
    "enable_fps_timer": "false",
    "debug_mode": "false" 
  },
  "analyzer_config": {
    "detection_area_factor": 0.001,
    "resize_width": 400,
    "gauss_blur_factor": 15,
    "bbox_mode": "false",
    "verbose": "true"

  },
  "file_writer_config": {

  }
}
